name: Fetch Stock OHLC Data Daily

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 3 AM UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  fetch_stock_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug - Show Current Directory
        run: pwd && ls -R

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug - Show Current Directory After Install
        run: pwd && ls -R

      - name: Run fetch script
        run: python fetch_stock_history.py  # ✅ Run the script

